spring:
  application:
    name: InsightHub

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

security:
  jwt:
    issuer: insighthub
    ttl-seconds: 3600