spring:
  datasource:
    url: jdbc:h2:mem:insighthub;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/common,classpath:db/migration/h2

  elasticsearch:
    uris: http://localhost:9200

