spring:
  application:
    name: InsightHub

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

security:
  jwt:
    issuer: insighthub
    ttl-seconds: 3600