-- =========================================================
-- USERS
-- =========================================================
CREATE TABLE users
(
    id            VARCHAR(255) PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE user_roles
(
    user_id   VARCHAR(255) NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role_name),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_permissions
(
    user_id    VARCHAR(255) NOT NULL,
    permission VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, permission),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- =========================================================
-- CATEGORIES
-- =========================================================
CREATE TABLE categories
(
    id        VARCHAR(255) PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,
    parent_id VARCHAR(255),
    FOREIGN KEY (parent_id) REFERENCES categories (id)
);

-- =========================================================
-- PRODUCTS
-- =========================================================
CREATE TABLE products
(
    id             VARCHAR(255) PRIMARY KEY,
    name           VARCHAR(255)   NOT NULL,
    description    VARCHAR(255),
    status         VARCHAR(255)   NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    price_amount   DECIMAL(19, 2) NOT NULL,
    price_currency VARCHAR(255)   NOT NULL,
    quantity       INTEGER        NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP      NOT NULL
);

-- =========================================================
-- PRODUCT_CATEGORIES
-- =========================================================
CREATE TABLE product_categories
(
    product_id  VARCHAR(255) NOT NULL,
    category_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (product_id, category_id),
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE INDEX idx_product_categories_category_id ON product_categories (category_id);

-- =========================================================
-- ORDERS
-- =========================================================
CREATE TABLE order_headers
(
    id             VARCHAR(255) PRIMARY KEY,
    user_id        VARCHAR(255) NOT NULL,
    status         VARCHAR(255) NOT NULL CHECK (status IN
                                                ('PENDING', 'RESERVED', 'PAID', 'FULFILLING', 'SHIPPED', 'COMPLETED',
                                                 'CANCELLED')),
    payment_status VARCHAR(255) NOT NULL CHECK (payment_status IN
                                                ('UNPAID', 'AUTHORIZED', 'CAPTURED', 'REFUNDED', 'FAILED')),
    created_at     TIMESTAMP    NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_order_headers_user_id ON order_headers (user_id);

CREATE TABLE order_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    VARCHAR(255)   NOT NULL,
    product_id  VARCHAR(255)   NOT NULL,
    name        VARCHAR(255)   NOT NULL,
    unit_amount DECIMAL(19, 2) NOT NULL,
    currency    VARCHAR(255)   NOT NULL,
    quantity    INTEGER        NOT NULL,
    FOREIGN KEY (order_id) REFERENCES order_headers (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);

-- =========================================================
-- NOTIFICATIONS
-- =========================================================
CREATE TABLE notifications
(
    id                VARCHAR(255) PRIMARY KEY,
    recipient_user_id VARCHAR(255),
    recipient_address VARCHAR(255),
    channel           VARCHAR(255) NOT NULL,
    subject           VARCHAR(255),
    body              TEXT         NOT NULL,
    status            VARCHAR(255) NOT NULL,
    priority          VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    sent_at           TIMESTAMP,
    read_at           TIMESTAMP
);

-- =========================================================
-- ANALYTICS
-- =========================================================
CREATE TABLE analytics_event_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key  VARCHAR(256) NOT NULL UNIQUE,
    created_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_analytics_event_log_created_at ON analytics_event_log (created_at);

CREATE TABLE analytics_daily_metrics
(
    day                  DATE         NOT NULL PRIMARY KEY,
    users_created        BIGINT       NOT NULL,
    orders_placed        BIGINT       NOT NULL,
    orders_paid          BIGINT       NOT NULL,
    orders_completed     BIGINT       NOT NULL,
    revenue_minor        BIGINT       NOT NULL,
    revenue_currency     VARCHAR(255) NOT NULL,
    notifications_sent   BIGINT       NOT NULL,
    notifications_failed BIGINT       NOT NULL
);
