-- =========================================================
-- USERS
-- =========================================================
CREATE TABLE users
(
    id            varchar(255)                NOT NULL PRIMARY KEY,
    email         varchar(255)                NOT NULL UNIQUE,
    password_hash varchar(255)                NOT NULL,
    first_name    varchar(255)                NOT NULL,
    last_name     varchar(255)                NOT NULL,
    status        varchar(255)                NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL
);

CREATE TABLE user_roles
(
    user_id   varchar(255) NOT NULL,
    role_name varchar(255) NOT NULL,
    PRIMARY KEY (user_id, role_name),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE TABLE user_permissions
(
    user_id    varchar(255) NOT NULL,
    permission varchar(255) NOT NULL,
    PRIMARY KEY (user_id, permission),
    CONSTRAINT fk_user_permissions_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE
);

-- =========================================================
-- CATEGORIES
-- =========================================================
CREATE TABLE categories
(
    id        varchar(255) NOT NULL PRIMARY KEY,
    name      varchar(255) NOT NULL UNIQUE,
    parent_id varchar(255) NULL,
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id) REFERENCES categories (id)
);

-- =========================================================
-- PRODUCTS (must exist before product_categories)
-- =========================================================
CREATE TABLE products
(
    id             varchar(255)                NOT NULL PRIMARY KEY,
    name           varchar(255)                NOT NULL,
    description    text                        NULL,
    status         varchar(255)                NOT NULL,
    price_amount   numeric(38, 2)              NOT NULL,
    price_currency varchar(255)                NOT NULL,
    quantity       integer                     NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,
    CONSTRAINT products_status_check
        CHECK ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

-- =========================================================
-- PRODUCT_CATEGORIES (join table)
-- =========================================================
CREATE TABLE product_categories
(
    product_id  varchar(255) NOT NULL,
    category_id varchar(255) NOT NULL,
    PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_categories_product
        FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_product_categories_category
        FOREIGN KEY (category_id) REFERENCES categories (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_product_categories_category_id
    ON product_categories (category_id);

-- =========================================================
-- ORDERS
-- =========================================================
CREATE TABLE order_headers
(
    id             varchar(255)                NOT NULL PRIMARY KEY,
    user_id        varchar(255)                NOT NULL,
    status         varchar(255)                NOT NULL,
    payment_status varchar(255)                NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    CONSTRAINT order_headers_payment_status_check
        CHECK ((payment_status)::text = ANY
               ((ARRAY ['UNPAID'::character varying, 'AUTHORIZED'::character varying, 'CAPTURED'::character varying, 'REFUNDED'::character varying, 'FAILED'::character varying])::text[])),
    CONSTRAINT order_headers_status_check
        CHECK ((status)::text = ANY
               ((ARRAY ['PENDING'::character varying, 'RESERVED'::character varying, 'PAID'::character varying, 'FULFILLING'::character varying, 'SHIPPED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))
);

CREATE INDEX idx_order_headers_user_id
    ON order_headers (user_id);

CREATE TABLE order_items
(
    id          bigint generated by default as identity PRIMARY KEY,
    order_id    varchar(255)   NOT NULL,
    product_id  varchar(255)   NOT NULL,
    name        varchar(255)   NOT NULL,
    unit_amount numeric(38, 2) NOT NULL,
    currency    varchar(255)   NOT NULL,
    quantity    integer        NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES order_headers (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id
    ON order_items (order_id);
